services:
  portal-plainvitamins:
    image: ghcr.io/kiznis-studio/portal-plainvitamins:latest
    container_name: portal-plainvitamins
    restart: unless-stopped
    volumes:
      - /opt/portals/data/sqlite/plainvitamins.db:/data/portal.db
    environment:
      - DATABASE_PATH=/data/portal.db
      - HOST=0.0.0.0
      - PORT=4321
      - CACHE_ENTRIES=5000
      - WORKERS=1
      - WORKERS_MAX=4
      - MGMT_PORT=4322
      - MAX_BOT_CONCURRENT=25
    networks:
      - portals
    mem_limit: 512m
    cpus: 0.5

networks:
  portals:
    external: true
    name: portals-net
